/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.project;

/**
 *
 * @author TANMOY
 */
public class catagory extends javax.swing.JFrame {

    /**
     * Creates new form catagory
     */
    public catagory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonElectronics = new javax.swing.JButton();
        buttonProperty = new javax.swing.JButton();
        buttonCloth = new javax.swing.JButton();
        buttonSports = new javax.swing.JButton();
        buttonFood = new javax.swing.JButton();
        buttonBusiness = new javax.swing.JButton();
        buttonEducation = new javax.swing.JButton();
        buttonAccessories = new javax.swing.JButton();
        buttonOthers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Catagory");

        buttonElectronics.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonElectronics.setText("Electronics");
        buttonElectronics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElectronicsActionPerformed(evt);
            }
        });

        buttonProperty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonProperty.setText("Property");
        buttonProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPropertyActionPerformed(evt);
            }
        });

        buttonCloth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonCloth.setText("Clothing,Health & Beauty");
        buttonCloth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClothActionPerformed(evt);
            }
        });

        buttonSports.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSports.setText("Sports & Travel");

        buttonFood.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonFood.setText("Food & Aggriculture");

        buttonBusiness.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonBusiness.setText("Business & Industry");
        buttonBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBusinessActionPerformed(evt);
            }
        });

        buttonEducation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonEducation.setText("Education");

        buttonAccessories.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAccessories.setText("Accessories");

        buttonOthers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonOthers.setText("Others");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonElectronics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCloth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBusiness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAccessories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonOthers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonElectronics)
                .addGap(4, 4, 4)
                .addComponent(buttonProperty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCloth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBusiness)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEducation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAccessories)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOthers))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPropertyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPropertyActionPerformed

    private void buttonClothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClothActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothActionPerformed

    private void buttonBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBusinessActionPerformed

    private void buttonElectronicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElectronicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElectronicsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catagory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccessories;
    private javax.swing.JButton buttonBusiness;
    private javax.swing.JButton buttonCloth;
    private javax.swing.JButton buttonEducation;
    private javax.swing.JButton buttonElectronics;
    private javax.swing.JButton buttonFood;
    private javax.swing.JButton buttonOthers;
    private javax.swing.JButton buttonProperty;
    private javax.swing.JButton buttonSports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
